apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: jobs-app
data:
#  NODE_ENV: "production"
  NODE_ENV: "development"
  PORT: "8000"
  MONGO_URI: "mongodb://mongodb:27017/jobsdb"
  FRONTEND_ORIGIN: "http://localhost:3000"
  ALLOWED_ORIGINS: "*"
# ALLOWED_ORIGINS: "http://localhost:3000,http://192.168.0.208:3000,http://192.168.56.200:30080,http://192.168.0.228:30080,http://192.168.0.229:30080,http://192.168.0.230:30080,http://192.168.0.231:30080"
  WORK24_KEY: "184d5b92-d9ef-4629-b9dc-1947635119ac"
  WORK24_BASE_URL: "https://www.work24.go.kr/cm/openApi/call/wk/callOpenApiSvcInfo210L21.do"