apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-registry
  namespace: jobs-app
spec:
  podSelector: {}  # 모든 파드에 적용
  policyTypes:
  - Egress
  egress:
  # Harbor 레지스트리 접근 허용
  - to:
    - ipBlock:
        cidr: 192.168.0.240/32  # Harbor 레지스트리 IP
    ports:
    - protocol: TCP
      port: 443  # HTTPS
    - protocol: TCP
      port: 80   # HTTP (필요한 경우)

